### ISSUE TITLE
Add a conda installation option using conda-forge channel

### ISSUE THREAD

**Issue by sugatoray** [koaning/doubtlab#14]
I have already started this one. Will push a PR once the `conda` installation option is available.

See: [Adding doubtlab from PyPI](https://github.com/conda-forge/staged-recipes/pull/16940) to `conda-forge` channel.

@koaning As the primary maintainer of this repo, would you like to be listed as one of the maintainers of `doubtlab` on `conda-forge` channel? Please let me know, I will add your name as another maintainer of `conda-forge/doubtlab-feedstock`, once it is accepted.

**Comment by koaning** [comment]
Ah sure, a conda distro would be grand. I'm not super familiar with conda though but please add me on the list. 

Is there a readme that describes the process you're following? I may have some other packages that I'd like to add.

**Comment by sugatoray** [comment]
I am putting together some material and various resources that I found useful for this purpose. I will share them with you. Hopefully, at some point in future, we will see another set of videos getting posted on Calmcode.io about publishing packages on `conda-forge` channel. :eyes: :wink:

**Comment by sugatoray** [comment]
:rocket: Good news: `doubtlab` is available on `conda-forge`. I will update the README with the conda installation option now.

Feedstock: https://github.com/conda-forge/doubtlab-feedstock
Conda: https://anaconda.org/conda-forge/doubtlab

![image](https://user-images.githubusercontent.com/10201242/144314355-069325e1-313e-47bf-bb7e-12bb717c2b0b.png)

cc: @koaning
