### ISSUE TITLE
Minor bug in LongConfidenceReason

### ISSUE THREAD

**Issue by adam444555** [koaning/doubtlab#40]
Hi, as stated in the title,
in reason.py line 260,
`proba_dict = {classes[j]: v for j, v in enumerate(proba) if j != y[i]}`
index j is compared to the class y[i]
suggested change:
`proba_dict = {classes[j]: v for j, v in enumerate(proba) if classes[j] != y[i]}`

**Comment by koaning** [comment]
That's not a minor bug 😅! Will have a look, you're also free to make the PR if you prefer.
