### ISSUE TITLE
Issue with cleanlab upgrading to v2

### ISSUE THREAD

**Issue by duarteocarmo** [koaning/doubtlab#43]
## Issue
![image](https://user-images.githubusercontent.com/26342344/164661446-fafe1fd3-a9ac-4059-b508-7372aa75650d.png)

## Environment details
![image](https://user-images.githubusercontent.com/26342344/164665464-938f1089-d35e-451a-85ae-1ca3ffc154ff.png)

## Temporary fix 
`pip install "doubtlab==1.0.0"`

## More permanent fix
Pin doubtlab dependency to "doubtlab<2.0.0"

## More more permanent fix
[They've made some changes to their API](https://docs.cleanlab.ai/v2.0.0/migrating/migrate_v2.html?highlight=pruning)

Let me know if you'd like me to make a PR 

Thanks for a great package @koaning  😄

**Comment by koaning** [comment]
PR: yes, please!

I think they released a new version yesterday that's breaking.
