### ISSUE TITLE
"Fair" Sorting 

### ISSUE THREAD

**Issue by koaning** [koaning/doubtlab#9]
Suppose there are 5 reasons for doubt, 4 of which overlap a lot. Then we may end up in a situation where we ignore a reason. That could be bad ... maybe it's worth exploring voting systems a bit to figure out alternative sorting methods.

**Comment by Garve** [comment]
We then have to define this overlap somehow, maybe starting from the overlap of two reasons. Let's take a supposedly easy one, maybe the `DisagreeReason` that outputs a 1 whenever two models disagree. If we use `DisagreeReason(model_a, model_b)` and `DisagreeReason(model_a, model_c)` for example, what should their overlap be? I think that is even hard to come up with something here, let alone for general reasons.

The only thing I can think of right now is using some kind of correlation of the outputs for two reasons. But then even two completely different, unrelated reasons could have a huge overlap (correlation close to or even 1) then.

**Comment by koaning** [comment]
Yeah, this is something that I'd like to investigate more. I suppose one approach is to use some sort of active learning trick on these predicates. If we eventually find that we flip a label, that could be used as a signal to improve the sorting.

**Comment by koaning** [comment]
Sure. 

Let's say we have a batch of data that is sorted based on a set of reasons by a `DoubtEnsemble`. This set of reasons is a dataframe where each column represents a reason. Let's say we look at the top 100 rows on our sorted original dataset. Some of these labels will be bad and should be flipped. Other rows of data are fine. 

In an attempt to see more examples that "should be flipped" we could train a classifier. This is just an idea though, dunno if it would work, but we could see our reasons as a feature generating trick for the task of "predicting a bad label".

**Comment by Garve** [comment]
Thanks for explaining, that sounds like an interesting approach! So we start with some dataset _X, y_ and create another dataset _X', y'_ with some binary _y'_ that says that the label looks fine vs the label looks bad. _X'_ is the output by the `DoubtEnsemble`? And then we train a classifier and sort the results using the `predit_proba` scores in descending order, right? Sounds reasonable to me, if I even got it right now :D

**Comment by koaning** [comment]
> X' is the output by the DoubtEnsemble?

Potentially! We could also `concat(X, X')`. But I should stress: let's try this idea out before we implement it into this library. It may be that implementing this falls outside the scope of this library. The only way to know for sure is to figure out how effective this "trick" might actually be.

**Comment by koaning** [comment]
This issue is more general though. The question is, given a set of reasons that indicate 0/1 ... what heuristic might we apply for ordering?
